Ameelio/letters-mobile

- .github/workflows/tsc.yml
- package-lock.json
- package.json
- src/navigations/index.tsx
- src/views/ReferFriends/ReferFriends.react.tsx
- test/views/__snapshots__/ReferFriends.test.tsx.snap
Created a new github action according to https://github.com/marketplace/actions/typescript-compiler to run typescript checks everytime a push / PR is made. Added the husky / prettier package along with a change to the package.json so that these code style fixes would automatically be made on commit.
Followed https://github.com/marketplace/actions/typescript-compiler to make the new github action. Followed https://create-react-app.dev/docs/setting-up-your-editor/ to add husky + prettier support. Made small edits to `ReferFriends.react.tsx` to fix typescript errors on master.
Makes sure that code that is pushed to master compiles well, with good style.
Noticed Husky working locally. We will see if the auto typescript check works after this PR lol.
> Implement husky linting and prettier on commit + typescript Checks on PR

- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/navigations/index.tsx
- src/store/Letter/LetterReducer.tsx
- src/views/AddContact/ReviewContact.react.tsx
- src/views/Home/SingleContact.react.tsx
- src/views/MemoryLane/MemoryLane.react.tsx
- src/views/MemoryLane/MemoryLane.styles.tsx
- src/views/UpdateContact/UpdateContact.react.tsx
- src/views/index.ts
- test/views/MemoryLane.test.tsx
- test/views/UpdateContact.test.tsx
- test/views/__snapshots__/MemoryLane.test.tsx.snap
Created a screen view for the "Memory Lane," which displays the cards for each letter written by the user to a specific contact.
- Created a view for "Memory Lane"
- Displayed the contact's letters in a two-column grid
- Pressing on them should navigate to a detailed view of the letter (upcoming PR)
- Wrote tests for Memory Lane and updated test for SingleContact view
https://github.com/Ameelio/letters-mobile/issues/37
* Passes `npm run test`
> Memory Lane Screen

- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/views/AddContact/AddManually.react.tsx
- src/views/AddContact/ContactInfo.react.tsx
- src/views/AddContact/FacilityDirectory.react.tsx
- src/views/AddContact/ReviewContact.react.tsx
- src/views/Home/ContactSelector.react.tsx
- test/views/__snapshots__/AddManually.test.tsx.snap
- test/views/__snapshots__/ContactInfo.test.tsx.snap
- test/views/__snapshots__/ContactSelector.test.tsx.snap
- test/views/__snapshots__/FacilityDirectory.test.tsx.snap
- test/views/__snapshots__/ReviewContact.test.tsx.snap
* Went through screens on master that did not have i18n translations
* Added i18n translations
* Added i18n translations for screens that did not yet have them
* Updated snapshot tests
* Accessibility of our app
* Clean-up existing screens
* Ran `npm run tests`
- [] I have added tests to cover my changes.
> [Quick][Clean-up] Add i18n Translations to Screens on Master Branch

- src/components/Card/MemoryLaneCard.react.tsx
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/navigations/index.tsx
- src/store/Letter/LetterReducer.tsx
- src/types.ts
- src/views/Home/SingleContact.react.tsx
- src/views/MemoryLane/LetterDetails.react.tsx
- src/views/MemoryLane/LetterDetails.styles.tsx
- src/views/MemoryLane/MemoryLane.react.tsx
- src/views/MemoryLane/MemoryLane.styles.tsx
- src/views/index.ts
- test/components/Card/__snapshots__/MemoryLaneCard.test.tsx.snap
- test/views/LetterDetails.test.tsx
- test/views/MemoryLane.test.tsx
- test/views/__snapshots__/LetterDetails.test.tsx.snap
- test/views/__snapshots__/MemoryLane.test.tsx.snap
* Created a screen to view the details of a letter (via pressing on a Memory Lane card)
* Created a screen
* Displayed date created, letter message, and letter photos (if any)
* Wrote unit tests
https://github.com/Ameelio/letters-mobile/issues/63
* Ran on iOS Device
* `npm run tests`
> Letter Details Screen

- src/styles/Colors.ts
- test/components/__snapshots__/LetterTracker.test.tsx.snap
- test/components/__snapshots__/Topbar.test.tsx.snap
- test/views/__snapshots__/ContactSelector.test.tsx.snap
- test/views/__snapshots__/LetterDetails.test.tsx.snap
- test/views/__snapshots__/LetterTracking.test.tsx.snap
- test/views/__snapshots__/Login.test.tsx.snap
- test/views/__snapshots__/SingleContact.test.tsx.snap
Introduce new color schemes into our app
* Added color schemes for pinkscale, bluescale, greenscale
* Updated color schemes for grayscale
https://github.com/Ameelio/letters-mobile/issues/29
* `npm run tests`
> [Quick][Mobile Component Library] Colors

- src/styles/Colors.ts
> [HOTFIX] colors

- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/navigations/index.tsx
- src/views/Compose/PostcardPreview.react.tsx
Update the titles of the screens in the compose flow to prevent errors
In new bars componenet, titles need to be specified but they were not for a recently merged compose branch, causing an error
Made it so in the future if this happens it does not error, but just sets a blank title and defaults `profile` to true
To not error
Errors don't occur
> [Hotfix] Compose titles

- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/navigations/index.tsx
- src/views/Login/Login.react.tsx
- src/views/Login/Privacy.react.tsx
- src/views/Login/Terms.react.tsx
- src/views/index.ts
- test/views/Login/Login.test.tsx
- test/views/Login/Privacy.test.tsx
- test/views/Login/Terms.test.tsx
- test/views/Login/__snapshots__/Privacy.test.tsx.snap
- test/views/Login/__snapshots__/Terms.test.tsx.snap
* Screens to display our Terms of Service and Privacy Policy
* Added in screens (texts will be completed by a follow-up task)
* Hooked into Login Screen
* Wrote basic unit tests 
* Legal reasons I think
* Ran `npm run test`
> [Screens] Terms of Service + Privacy Policy

- src/assets/views/Onboarding/Checked.ts
- src/assets/views/Onboarding/Unchecked.ts
- src/views/Login/Login.react.tsx
- src/views/Register/Register.react.tsx
- test/views/Login/__snapshots__/Login.test.tsx.snap
- test/views/Register/__snapshots__/Register.test.tsx.snap
* Added checked and unchecked SVG icons for `Remember Me` checkboxes
* Checked icons + unchecked icons
* Bug bash!
* `npm run test`
> [Bug Bash][EZ] Checkbox Icons

- src/api/index.ts
- src/views/Home/SingleContact.react.tsx
- test/views/Home/__snapshots__/SingleContact.test.tsx.snap
* Before, the new added contact was not showing up in the list of `ContactSelector` after finishing the `AddContact` flow
* I think the issue we were updating the reducer in the API had some unexpected behavior 
* Decided to create a new array to copy over existing contacts and add in new contact (this probably won't be too expensive of an action to loop through all contacts since most users have 1 contact)
* Also increased the height of the view for the pencil icon so it was easier to press to access the `UpdateContact` screen
* Bug bash!
* `npm run test`
> [BugBash][EZ] Fix Adding Contact Flow

- src/navigations/index.tsx
hot hot fix
* We accidentally removed the ChooseOption screen as our initial screen
> [hotfix] add back ChooseOption screen

- src/api/index.ts
- src/i18n/locales/en.json
- src/views/Compose/ComposeLetter.react.tsx
- src/views/Compose/ComposePostcard.react.tsx
- src/views/Home/ContactSelector.react.tsx
- src/views/Login/Login.react.tsx
- src/views/Register/Register.react.tsx
- src/views/UpdateContact/UpdateContact.react.tsx
- test/views/Login/__snapshots__/Login.test.tsx.snap
- test/views/Register/__snapshots__/Register.test.tsx.snap
Yellow warning. No empty letters. Register bug. Update contact photo shows up immediately.
Bugs
bugs bad
updated tests
> Final Bugs

- src/components/PicUpload/PicUpload.react.tsx
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/views/AddContact/FacilityDirectory.react.tsx
- src/views/Compose/ComposeLetter.react.tsx
- src/views/Home/ContactSelector.react.tsx
- src/views/UpdateContact/UpdateContact.react.tsx
- test/views/Compose/__snapshots__/ComposeLetter.test.tsx.snap
- test/views/Update/__snapshots__/UpdateContact.test.tsx.snap
Went through the Issues cards and fixed up several bugs
* Initial upload photo (for avatars) shows a white circle with an 'X' instead of the camera icon
* Allow user to see full image in the letter preview screen
* No image icon in keyboard bar of letters
* Display text when there are no contacts
* Make our app more robust
Closes #110 
Closes #107 
Closes #105 
Closes #101 
* `npm run test`
> [Bug Bash][EZ] Various Bugs

- src/components/Input/Input.react.tsx
- src/i18n/locales/en.json
- src/utils/index.ts
- src/views/AddContact/AddManually.react.tsx
- src/views/AddContact/ContactInfo.react.tsx
- src/views/Login/Login.react.tsx
- src/views/Register/Register.react.tsx
- src/views/UpdateContact/UpdateContact.react.tsx
- src/views/UpdateProfile/UpdateProfile.react.tsx
- test/views/Login/Login.test.tsx
- test/views/Register/__snapshots__/Register.test.tsx.snap
- test/views/Update/__snapshots__/UpdateProfile.test.tsx.snap
Fixed up a bunch of miscellaneous bugs relating to the input component and how it is used in login.
Added extra validation to address, city, and inmateNumber to prevent things like emojis and unsupported characters to these inputs.
We want to catch typos or emojis early so letters are not sent with incorrect details.
Closes #147 
Closes #140
Closes #128
Closes #132
Closes #139
> [Bugs] Various input / login bugs

- src/components/PicUpload/PicUpload.react.tsx
- src/views/Compose/ChooseOption.react.tsx
- src/views/Compose/LetterPreview.react.tsx
- src/views/Compose/PostcardPreview.react.tsx
Fixed issue of contact images being non-square and sent letters being considered drafts.
Made sure contact profile images have square dimensions and that sent letters do not count as drafts after they are sent.
Bugs.
Update tests.
> [Bugs] Fix non-square images and non-existent letter draft after send

- package-lock.json
- package.json
- src/api/User.ts
- src/components/PicUpload/PicUpload.react.tsx
- src/index.tsx
- src/views/Compose/ChooseOption.react.tsx
- src/views/Compose/ComposeLetter.react.tsx
- src/views/Compose/ComposePostcard.react.tsx
- src/views/Compose/LetterPreview.react.tsx
- src/views/Compose/PostcardPreview.react.tsx
- src/views/Home/ContactSelector.react.tsx
- src/views/LetterTracking/LetterTracking.react.tsx
- src/views/MemoryLane/MemoryLane.react.tsx
- src/views/Report/Issues.react.tsx
- src/views/Report/SupportFAQ.react.tsx
- src/views/UpdateContact/UpdateContact.react.tsx
- src/views/UpdateProfile/UpdateProfile.react.tsx
* Integrated `expo-analytics-segment` into the project
* Added most of my tracking events into the `Compose` flow 
* Added tracking events for `UpdateContact` and `UpdateProfile`
* Added more params to `PicUpload` to handle success and error logging
* Stats and cool graphs!
* Ran through the flows and saw the logs appear in the debugger on Segment portal
Example of some logs:
> [Segment] Integrate Expo Segment + Logging Events

- test/components/Card/ContactSelectorCard.test.tsx
- test/components/Card/__snapshots__/ContactSelectorCard.test.tsx.snap
- test/views/Home/SingleContact.test.tsx
- test/views/Home/__snapshots__/SingleContact.test.tsx.snap
Flaky date tests in `ContactSelectorCard` and `SingleContactScreen`
Tests were flaky because forgot to mock out `moment` functions
Be stable
`npm run tests`
> [hotfix] fix flaky snapshots

- src/api/Facilities.ts
- src/components/Card/PrisonCard.react.tsx
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/types.ts
- src/views/AddContact/FacilityDirectory.react.tsx
- test/components/Card/PrisonCard.test.tsx
Supporting all types of facilities
Facility strings are showing on the app
> supporting more facilitty types

- app.json
Add in iOS specific plist changes so users know why the app requests certain permissions.
> [EZ] Plist changes

- package-lock.json
- package.json
- src/api/User.ts
- src/views/AddContact/ReviewContact.react.tsx
- src/views/Compose/LetterPreview.react.tsx
- src/views/Compose/PostcardPreview.react.tsx
- src/views/Compose/ReferFriends.react.tsx
- src/views/Report/Issues.react.tsx
- src/views/Report/IssuesDetail.react.tsx
- src/views/Report/IssuesDetailSecondary.react.tsx
> fixed trackings

- app.config.js
- app.json
- package-lock.json
- package.json
- src/index.tsx
> added sentry, fixed photo bug on android

- src/assets/views/ContactSelector/AddContact.ts
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/views/Home/ContactSelector.react.tsx
- src/views/Home/ContactSelector.styles.tsx
- src/views/Home/MailTracking.react.tsx
- test/views/Home/ContactSelector.test.tsx
- delete floating plus button 
- add Add Contact button at bottom of contacts list
closes #184 
https://drive.google.com/file/d/1ysI6iZkf-gvFuNabI0flnBkthJ4_VRvj/view?usp=sharing
> [ContactSelector] update Add Contact button

- src/components/Card/CategoryCard.react.tsx
- src/navigations/index.tsx
- src/views/Compose/ComposeLetter.react.tsx
- src/views/Compose/ComposePostcard.react.tsx
- src/views/Compose/ReviewLetter.react.tsx
- src/views/Compose/ReviewPostcard.react.tsx
- src/views/Home/ContactSelector.styles.tsx
- src/views/Login/Login.react.tsx
- src/views/Update/UpdateContact.react.tsx
- src/views/Update/UpdateProfile.react.tsx
- fixed some issues with scrolling
- fixed tiny padding issue
- removed undefined params bug on referfriends (highest priority)
> [Bugs] Final tweaks

- src/index.tsx
- src/utils/index.ts
> Final for real

- src/index.tsx
- src/utils/index.ts
Restored the isProduction function to work on dev.
> [BUG] Restore isProduction() in dev branch

- src/components/Card/MemoryLaneCard.react.tsx
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/views/MemoryLane/MailDetails.react.tsx
- copy: change "Review" to "Preview" in Postcard Review screeen
- style: make Memory Lane Card and Mail Detail use REGULAR weight font
part of #251 
Before & after
Before & after
> minor fixes

- src/navigations/index.tsx
- src/views/AddContact/AddManually.react.tsx
- src/views/AddContact/FacilityDirectory.react.tsx
- src/views/AddContact/ReviewContact.react.tsx
- src/views/Compose/ComposePostcard.react.tsx
- src/views/Compose/ReviewPostcard.react.tsx
Fixes the tracks on the send postcard and add contact
Removes bug, fixes things.
Closes #259 
Closes #254
Checked tracks on segment staging.
> [Segment] Fix send postcard and add contact tracks

- src/components/Input/Input.react.tsx
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/index.tsx
- src/notifications/index.ts
- src/views/Home/MailTracking.react.tsx
- src/views/Home/SingleContact.react.tsx
Fixed (or at least I'm pretty sure) all open sentry issues.
- added try catch blocks around notification cancelling so if a notification is attempted to be cancelled twice it does not err.
- added a check that a `value` string in the input component to avoid the `n.length` error
- added try catch block around loading tracking events to avoid the `non-error exception captured with...` error.
Closes #270 
Closes #269 
Closes #268 
Closes #275
> [Sentry + Segment] Fix open sentry issues and segment tracks

- package-lock.json
- package.json
- src/api/Mail.ts
- src/api/User.ts
- src/views/Compose/ChooseCategory.react.tsx
- src/views/Home/ContactSelector.react.tsx
Fixed a couple relase blocking bugs from friday.
Fixed the bug where if one call to `getSize` fails then the whole `getCategories` call fails. Reduced the number of backend calls on the contact selector screen.
> [Compose] Fix design bugs.

- app.json
Update version codes to 1.1.1 before publish. Remember to change the .env file before buiding as well!
> [Publish] v1.1.1

- src/components/StaticPostcard/StaticPostcard.react.tsx
- src/navigations/index.tsx
- src/views/Compose/ChooseCategory.react.tsx
Removed duplicate route red errors, bump lines in postcard preview to 12.
> [bugs] bump to 12 lines, hot fix

- src/utils/index.ts
- src/views/Compose/ReviewLetter.react.tsx
- src/views/Compose/ReviewPostcard.react.tsx
Hotfix for issues caused by merge of old open PR dealing with notif logic.
Fixed a misimport and refactored to avoid a circular dependency.
> [Hotfix] Import error + circular dependencies

- src/components/PicUpload/PicUpload.react.tsx
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/utils/index.ts
- src/views/AddContact/FacilityDirectory.react.tsx
- src/views/Update/UpdateContact.react.tsx
before
1. facilities listed in random order
2. if user uploads portrait mode image, the top and bottom are cut off (because height/width are swapped)
3. can't update contact's Inmate Number
after
1. facilities display in alphabetical order (this feels more standard to me, but happy to change it back if we don't wanna sort each time) 
2. use correct dimensions of uploaded portrait mode image (using exif) -- if the orientation is 5,6,7,8, that means image is rotated and so height and width need to be swapped
3. can update Inmate Number
> some quick fixes

- src/components/ComposeTools/ComposeTools.react.tsx
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/utils/index.ts
- src/views/Compose/ComposeLetter.react.tsx
- src/views/Compose/ComposePostcard.react.tsx
- src/views/Home/MailTracking.react.tsx
- src/views/Home/MailTracking.styles.tsx
Checked with Joyce and we can actually do 100 words
More writing = more fun!
On my phone
> bumping postcards from 300 chars to 100 words

- src/api/Mail.ts
- src/types.ts
- src/views/Compose/ComposePostcard.react.tsx
- src/views/Compose/ReviewPostcard.react.tsx
Add segment tracks for content_researcher and designer.
Added new fields in the three relevant segment tracks.
Give us more information on which designs / volunteers are being chosen by users.
Tested on staging.
> [Segment] Track new design fields

- src/views/Home/ContactSelector.react.tsx
> small fix to notif

- src/api/Common.ts
- src/api/Mail.ts
- src/components/ComposeTools/ComposeTools.react.tsx
- src/components/DynamicPostcard/DynamicPostcard.react.tsx
- src/views/Compose/Compose.styles.tsx
- src/views/Compose/ComposePersonal.react.tsx
- src/views/Compose/ComposePostcard.react.tsx
- src/views/Compose/ReferFriends.react.tsx
- src/views/Compose/ReferFriends.style.tsx
- src/views/Compose/ReviewLetter.react.tsx
Bugs that were in Slack DMs, plus few small things I noticed that looked strange on big screen bc updates for small screens, tested on both now.
> [Bugs] Final bug fixes + resolving some changes made to optimize small screens to work well with big screens as well

- app.json
- src/notifications/index.ts
> [Publish] v3

- src/api/Mail.ts
- src/api/User.ts
- src/components/DynamicPostcard/DynamicPostcard.react.tsx
- src/components/DynamicPostcard/DynamicPostcard.styles.tsx
- src/components/LetterTracker/LetterTracker.react.tsx
- src/components/ProfilePic/ProfilePic.react.tsx
- src/store/Mail/MailActions.tsx
- src/store/Mail/MailReducer.tsx
- src/store/Mail/MailTypes.tsx
- src/store/User/UserActions.ts
- src/store/User/UserReducer.ts
- src/store/User/UserTypes.ts
- src/utils/index.ts
- src/views/Compose/ComposePersonal.react.tsx
- src/views/Home/MailTracking.react.tsx
- src/views/Home/SingleContact.react.tsx
- src/views/Login/Splash.react.tsx
- src/views/Referrals/ReferralDashboard.react.tsx
> [Bugs] Patch v3

- src/api/User.ts
- src/views/Compose/ReferFriends.react.tsx
- src/views/Home/SingleContact.react.tsx
> leveraging parallelsm

- app.json
> bumped app.json

- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/utils/index.ts
- src/views/Compose/ReviewLetter.react.tsx
- src/views/Compose/ReviewPostcard.react.tsx
> [Compose] Show modal when generic error

- app.json
- src/components/Card/ContactSelectorCard.react.tsx
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/utils/index.ts
Bump version, transition to using 'days ago', quick fixes
> [Patch] v1.2.4

- src/api/Contacts.ts
- src/components/Card/Card.styles.tsx
- src/components/Card/ContactSelectorCard.react.tsx
- src/store/Contact/ContactReducer.tsx
- src/styles/Colors.ts
- src/types.ts
- src/views/Home/ContactSelector.react.tsx
- src/views/Home/ContactSelector.styles.tsx
- src/views/Home/SingleContact.react.tsx
Small tweaks on new contact selector card. @gabrielsaruhashi my iPhone might be out of commission for a bit, so if you could test if this resolves the iPhone specific bugs on your phone + fix if not that would be awesome
Closes #361
> [ContactSelector] Fix card

- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/views/AddContact/ReviewContact.react.tsx
Modal + better segment/sentry logging when add contact fails
We got a 1-star review bc user couldn't get past the add contact screen. Similar to send letter failure solution.
IPhone
> better error handling for add contact

- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/views/Onboarding/Begin.styles.tsx
> translation debt, and tiny text for begin

- src/api/Mail.ts
- src/api/Premium.ts
- src/api/User.ts
- src/store/Premium/PremiumActions.tsx
- src/store/Premium/PremiumReducer.tsx
- src/store/Premium/PremiumTypes.tsx
- src/types.ts
- src/views/Compose/ChooseOption.react.tsx
- src/views/Compose/SelectPostcardSize.styles.tsx
> [Premium] typescript and api groundwork for premium store

- src/api/Premium.ts
- src/api/User.ts
- src/api/index.ts
- src/components/Card/Card.styles.tsx
- src/components/Card/TransactionHistoryCard.react.tsx
- src/components/Loaders/TransactionPlaceholder.tsx
- src/components/index.ts
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/navigations/Store.tsx
- src/store/Contact/ContactActions.tsx
- src/store/Contact/ContactReducer.tsx
- src/store/Contact/ContactTypes.tsx
- src/store/Mail/MailActions.tsx
- src/store/Mail/MailReducer.tsx
- src/store/Mail/MailTypes.tsx
- src/store/Premium/PremiumActions.tsx
- src/store/Premium/PremiumReducer.tsx
- src/store/Premium/PremiumTypes.tsx
- src/types.ts
- src/utils/Screens.ts
- src/views/Store/Store.react.tsx
- src/views/Store/TransactionHistory.react.tsx
- src/views/Store/TransactionHistory.styles.tsx
- src/views/index.ts
Outline of work for the transaction history page.
Implemented the mockup.
Closes #406 
Pixel.
> [Premium] Transaction history initial work

- src/components/Alert/Alert.react.tsx
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/notifications/index.ts
- src/store/Premium/PremiumActions.tsx
- src/store/Premium/PremiumReducer.tsx
- src/store/Premium/PremiumTypes.tsx
- src/views/Home/ContactSelector.react.tsx
Dynamic modal title. Display + save in store.
Added support for a dynamic modal title (emojis). Display the "Explore store modal" once per user as stored in store.
Begins work on #413 but does not close
> [Store] Modal for getting to store.
